### ISSUE TITLE
Can I use show() in ManagedScreen class or use create() only

### ISSUE THREAD

**Issue by wangdong20** [crykn/libgdx-screenmanager#24]
I want to rewrite Libgdx screen system to this library managed screen system. In my original screen, I wrote a lot of code in show(), should I move those code to create() in ManagedScreen or just leave it? I have no idea why you  import create() interface in ManagedScreen to rewrite show() interface which change a lot for the original Screen class.

**Comment by crykn** [comment]
The initial goal of splitting the screen creation into the constructor and the create() method was to allow deferring the  initialization of screens. This can come in handy if you are using a loading screen to load your assets: At the start, you can create your screen (and do stuff in its constructor), even when your assets aren't loaded yet; `create()` is then only called when your assets are already loaded (either via the loading screen calling `ManagedScreen#initializeScreen()` (which internally calls `create()`) or automatically when the screen is first shown (by default `create()` is called right before the screen is first shown)). 

As I've stated [here](https://github.com/crykn/libgdx-screenmanager/issues/23#issuecomment-1582383322), as the library has become bigger this has turned out to be somewhat confusing for new users and I'm not really sure whether this couldn't be handled in a better manner in future releases. Maybe it'd make sense to combine it with a dependency injection system (so you wouldn't have to hand over everything via the new screen's constructor), but that is a problem for another day.

To get back to your question: if your stuff was in libGDX's `show()` method, it can stay there in libgdx-screenmanager's `show()` method. Both of those are called whenever the screen is shown. On the other hand, libgdx-screenmanager's `create()` method is only called once (!) and can be seen as a replacement for the screen's constructor.

All of this is also detailed [here](https://github.com/crykn/libgdx-screenmanager/wiki/Screen-Lifecycle) and [here](https://github.com/crykn/libgdx-screenmanager/wiki/Where-to-initialise-screens-and-transitions) in the wiki, so be sure to check that out too.

**Comment by wangdong20** [comment]
Is it required to call super.show() before the code block in show() in libgdx-screenmanager system?
After reading the code from ManagedScreen, I think it is required.

**Comment by crykn** [comment]
Yes, you should.
