### ISSUE TITLE
Cannot access ManagedGame

### ISSUE THREAD

**Issue by therevills** [crykn/libgdx-screenmanager#27]
Trying to copy the example but get the error Cannot access ManagedGame when running the DesktopLauncher:

`E:\Dropbox\AndroidDev\Test\desktop\src\com\therevillsgames\test\DesktopLauncher.java:16: error: cannot access ManagedGame
			new Lwjgl3Application(new MyGdxGame(), config);
			^
  class file for de.eskalon.commons.core.ManagedGame not found`

**Comment by crykn** [comment]
This error indicates that there's an issue with your dependencies. Judging by your message on the libGDX Discord, `guacamole` cannot be resolved, which can happen when Jitpack misbehaves. This should be easily fixed by adding `com.github.crykn.guacamole:gdx:v0.3.3` (note the v before the version!) as a separate dependency.
