### ISSUE TITLE
Inconsistencies between libgdxs implementation of setScreens() and screenmanager.

### ISSUE THREAD

**Issue by lyze237** [crykn/libgdx-screenmanager#6]
Hello!

Thanks for the awesome library, it's great so far.

I noticed a difference though (as far as I understand the code) between libgdx's game class and your ManagedGame class.

The only time screenmanager calls `resize()` on (initialized only) screens itself is [when the window actually gets resized.](https://github.com/crykn/libgdx-screenmanager/blob/master/src/main/java/de/eskalon/commons/screen/ScreenManager.java#L368)
```java
for (S s : screens.values()) {
	if (s.isInitialized()) {
		s.resize(width, height);
	}
}
```

This is problematic since the window could get resized before a screen could be initialized. Therefore the screen could render in a different resolution.

Obviously a simple fix is to override `show()` like this:
```java
@Override
public void show() {
	super.show();

	resize(Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
}
```

However this means every `show()` needs to be overridden like that that and I think it'd be better to include that in the library itself similar to how libgdx does it:

When you call [setScreen(Screen screen)](https://github.com/libgdx/libgdx/blob/a4805d6a017b80622d6bfdd3a791352257a3c539/gdx/src/com/badlogic/gdx/Game.java#L62) in libgdx it calls `resize()` on the screen directly afterwards.
```java
public void setScreen (Screen screen) {
	if (this.screen != null) this.screen.hide();
	this.screen = screen;
	if (this.screen != null) {
		this.screen.show();
		this.screen.resize(Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
	}
}
```

Example:
![we9G7Bdrol](https://user-images.githubusercontent.com/11274700/86808576-49ce7900-c07b-11ea-920a-81b1aa29a1f9.gif)

What's your opinion on this?

**Comment by crykn** [comment]
Hey lyze237,

thanks for your interest in screenmanager!

You're right, `resize()` is not called on a screen, when the game was resized before the screen was initialised. My reasoning for this was that every screen gets initialised before being shown, so the "initial sizing" can happen there (i.e. in `create()`) instead of in `resize()`. 

As most of my games can't be resized, I never had an issue with this. However, I can see a problem with this approach: in most cases this leads to just calling `resize()` in your `create()` method, a rather unnecessary duplication of code.

A fix for this would be to  call `resize()` on every screen once right after it was initialised (so right after `create()` was called). Would this be an appropriate solution for you?

---

As an interim solution:

You can use a custom screen class with your screenmanager. So instead of adding `resize(Gdx.graphics.getWidth(), Gdx.graphics.getHeight());` to every single one of your screens you can  just add it once to a common super class of all your screens:

```java
public abstract class MyScreen extends ManagedScreen {
	@Override
	public void show() {
		super.show();
		resize(Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
	}
}
```

**Comment by lyze237** [comment]
> Would this be an appropriate solution for you?
Yeah that sounds like the perfect solution.

I'll extend a class in the meantime.

Thanks :)

**Comment by crykn** [comment]
@lyze237 if you want to use the fix, you can use the following dependency:

```java
implementation 'com.github.crykn:libgdx-screenmanager:237ced8304'
```
